services:
  mongo:
    image: mongo:7
    pull_policy: always
    container_name: todo-mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: rishavpatel05/todo-backend:latest
    pull_policy: always
    container_name: todo-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    depends_on:
      mongo:
        condition: service_healthy

  frontend:
    image: rishavpatel05/todo-frontend:latest
    pull_policy: always
    container_name: todo-frontend
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    environment:
      - BACKEND_URL=http://backend:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo_data:
